In [1]:
import numpy as np

# -------------------------------
# Step 1: Define Hopfield Network
# -------------------------------
class HopfieldNetwork:
    def __init__(self):
        self.W = None

    def train(self, patterns):
        """Train network using Hebb's Rule"""
        n = patterns.shape[1]
        self.W = np.zeros((n, n))

        for p in patterns:
            p_bipolar = 2 * p - 1   # Convert (0,1) → (-1,+1)
            self.W += np.outer(p_bipolar, p_bipolar)

        np.fill_diagonal(self.W, 0)

        print("\nWeight Matrix:")
        print(self.W)

    def recall(self, pattern, max_steps=100):
        """Recall stored pattern"""
        x = 2 * pattern - 1

        for step in range(max_steps):
            x_new = x.copy()

            for i in range(len(x)):
                net_input = np.dot(self.W[i], x)
                x_new[i] = 1 if net_input >= 0 else -1

            if np.array_equal(x, x_new):
                print(f"Converged in {step+1} steps")
                break

            x = x_new

        return (x + 1) // 2


# -------------------------------
# Step 2: User Input for Patterns
# -------------------------------
num_patterns = int(input("Enter number of patterns: "))
num_elements = int(input("Enter number of elements in each pattern: "))

patterns = []

print("\nEnter patterns (only 0 and 1):")
for i in range(num_patterns):
    p = list(map(int, input(f"Pattern {i+1}: ").split()))
    
    if len(p) != num_elements:
        print("Invalid length! Try again.")
        exit()
    
    patterns.append(p)

patterns = np.array(patterns)

print("\nStored Patterns:")
for i, p in enumerate(patterns):
    print(f"Pattern {i}: {p}")


# -------------------------------
# Step 3: Train Network
# -------------------------------
hop = HopfieldNetwork()
hop.train(patterns)


# -------------------------------
# Step 4: Recall Stored Patterns
# -------------------------------
print("\nRecall Stored Patterns:")
for p in patterns:
    recalled = hop.recall(p)
    print("Input:", p, "→ Recalled:", recalled)


# -------------------------------
# Step 5: Test with Noisy Input
# -------------------------------
noisy = list(map(int, input("\nEnter noisy input: ").split()))

if len(noisy) != num_elements:
    print("Invalid noisy input length!")
    exit()

noisy = np.array(noisy)

print("\nNoisy Input:", noisy)

recalled = hop.recall(noisy)
print("Recalled Output:", recalled)

# Find closest pattern
distances = [np.sum(np.abs(recalled - p)) for p in patterns]
index = np.argmin(distances)

print("Closest Pattern:", patterns[index])

Enter number of patterns:  2
Enter number of elements in each pattern:  4



Enter patterns (only 0 and 1):


Pattern 1:  0 0 1 0
Pattern 2:  0 0 1 1



Stored Patterns:
Pattern 0: [0 0 1 0]
Pattern 1: [0 0 1 1]

Weight Matrix:
[[ 0.  2. -2.  0.]
 [ 2.  0. -2.  0.]
 [-2. -2.  0.  0.]
 [ 0.  0.  0.  0.]]

Recall Stored Patterns:
Converged in 2 steps
Input: [0 0 1 0] → Recalled: [0 0 1 1]
Converged in 1 steps
Input: [0 0 1 1] → Recalled: [0 0 1 1]



Enter noisy input:  0 0 1 0



Noisy Input: [0 0 1 0]
Converged in 2 steps
Recalled Output: [0 0 1 1]
Closest Pattern: [0 0 1 1]
