In [8]:
import numpy as np

class ART1:
    def __init__(self, num_features, max_clusters, vigilance=0.5):
        self.num_features = num_features
        self.max_clusters = max_clusters
        self.vigilance = vigilance
        
        self.W = np.ones((max_clusters, num_features))  # bottom-up weights
        self.T = np.ones((max_clusters, num_features))  # top-down weights
        self.cluster_count = 0

    def choice_function(self, x):
        return np.sum(np.minimum(self.W, x), axis=1) / (0.5 + np.sum(self.W, axis=1))

    def match_function(self, x, j):
        return np.sum(np.minimum(x, self.T[j])) / np.sum(x)

    def train(self, X):
        clusters = []

        for x in X:
            assigned = False
            visited = [False] * self.max_clusters

            while not assigned:
                T_values = self.choice_function(x)
                j = np.argmax(T_values)

                if visited[j]:
                    break

                visited[j] = True

                if self.match_function(x, j) >= self.vigilance:
                    # Update weights
                    self.W[j] = np.minimum(self.W[j], x)
                    self.T[j] = self.W[j]
                    clusters.append(j)
                    assigned = True
                else:
                    T_values[j] = -1  # inhibit

            if not assigned:
                if self.cluster_count < self.max_clusters:
                    j = self.cluster_count
                    self.W[j] = x
                    self.T[j] = x
                    clusters.append(j)
                    self.cluster_count += 1
                else:
                    clusters.append(-1)

        return clusters


# -------------------------------
# USER INPUT SECTION
# -------------------------------

# Number of patterns
n = int(input("Enter number of input patterns: "))

# Number of features
m = int(input("Enter number of features in each pattern: "))

# Input patterns
X = []
print("\nEnter binary patterns (0 or 1 only):")
for i in range(n):
    row = list(map(int, input(f"Pattern {i+1}: ").split()))
    X.append(row)

X = np.array(X)

# Max clusters
max_clusters = int(input("\nEnter maximum number of clusters: "))

# Vigilance parameter
vigilance = float(input("Enter vigilance parameter (0 to 1): "))


# -------------------------------
# TRAIN ART1 NETWORK
# -------------------------------

art = ART1(num_features=m, max_clusters=max_clusters, vigilance=vigilance)

clusters = art.train(X)


# -------------------------------
# OUTPUT
# -------------------------------

print("\nInput Patterns:")
print(X)

print("\nCluster Assignments:")
for i, c in enumerate(clusters):
    print(f"Pattern {i+1} -> Cluster {c}")

Enter number of input patterns:  4
Enter number of features in each pattern:  3



Enter binary patterns (0 or 1 only):


Pattern 1:  0 0 1
Pattern 2:  0 0 1
Pattern 3:  1 1 0
Pattern 4:  1 0 1

Enter maximum number of clusters:  3
Enter vigilance parameter (0 to 1):  0.6



Input Patterns:
[[0 0 1]
 [0 0 1]
 [1 1 0]
 [1 0 1]]

Cluster Assignments:
Pattern 1 -> Cluster 0
Pattern 2 -> Cluster 0
Pattern 3 -> Cluster 1
Pattern 4 -> Cluster 0
